apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-i77m
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ynew-tenant/quarkus/devfile-sample-code-with-quarkus-i77m@sha256:ff61710420580ce00a7be977f71e8779ad32146e527bfdaf4161dbe0413afd13
        name: my-java-quarkus
        resources: {}
status: {}
